/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import dao.AcademicoDAO;
import dao.FamilyDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Estudio;
import models.Funcionario;
import models.GrupoFamiliar;

/**
 *
 * @author ander
 */
public class listview extends javax.swing.JFrame {
    DefaultTableModel tb = new DefaultTableModel();
    DefaultTableModel tb2 = new DefaultTableModel();
    AcademicoDAO ad = new AcademicoDAO();
    FamilyDao n = new FamilyDao();
    FamilyView fv;
    AcademicoView av = new AcademicoView();
    
    private Funcionario fi;
    private JFrame j;
    /**
     * Creates new form listview
     */
    public listview(Funcionario fi, JFrame j) throws SQLException, ClassNotFoundException {
        this.fi = fi;
        initComponents();
        setTbf();
        GenerarDataF();
        setTbA();
        GenerarDataA();
        this.j =j;
        this.j.setVisible(false);
    }

    private listview() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    listview(Funcionario f) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
    
    public void setTbA(){
        String[] Cabecera = { "ID","Universidad", "Nivel","titulo"};
        tb2.setColumnIdentifiers(Cabecera);
        estudios.setModel(tb2);
        
    }
    
    public void GenerarDataA() throws SQLException, ClassNotFoundException{
        String[] valores = new String[4];
        List<Estudio> x = ad.listAll(fi.getId());
        for(Estudio m : x){
            valores[0]=String.valueOf(m.getId());
            valores[1]=m.getUniversidad();
            valores[2]=m.getNivelEstudio();
            valores[3]= m.getTitulo();
            
            tb2.addRow(valores);
        }
    }
    
    
    public void setTbf(){
        String[] Cabecera = { "ID","Nombre", "Rol","Recha de Nacimiento"};
        tb.setColumnIdentifiers(Cabecera);
        familiares.setModel(tb);
        
    }
    
    public void GenerarDataF() throws SQLException, ClassNotFoundException{
        String[] valores = new String[4];
        List<GrupoFamiliar> x = n.listAll(fi.getId());
        for(GrupoFamiliar m : x){
            valores[0]= String.valueOf(m.getId());
            valores[1]=m.getNombreFamiliar();
            valores[2]=m.getRol();
            valores[3]= m.getFechaNacimiento();
            System.out.println(valores);
            tb.addRow(valores);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        familiares = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        estudios = new javax.swing.JTable();
        back = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        familiares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        familiares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                familiaresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(familiares);

        estudios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        estudios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estudiosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(estudios);

        back.setText("Atras");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void familiaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_familiaresMouseClicked
        
        try {
            int fila = familiares.rowAtPoint(evt.getPoint());
            int idF = Integer.parseInt((String) tb.getValueAt(fila, 0));
            
            GrupoFamiliar xy =n.getById(idF);
            fv = new FamilyView(xy, listview.this);
            fv.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(listview.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(listview.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_familiaresMouseClicked

    private void estudiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estudiosMouseClicked
        try {
            int fila = estudios.rowAtPoint(evt.getPoint());
            int idF = Integer.parseInt((String) tb2.getValueAt(fila, 0));
            
            Estudio xy =ad.getById(idF);
            av = new AcademicoView(xy, listview.this);
            av.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(listview.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(listview.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_estudiosMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        j.setVisible(true);
        listview.this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTable estudios;
    private javax.swing.JTable familiares;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
